#端口号
server:
  port: 9000
#服务名
spring:
  application:
    name: Shop-banner
  profiles:
    active: mysql
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
